# Generated by Django 3.2.10 on 2025-01-09 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('minimo_jugadores', models.IntegerField()),
                ('maximo_jugadores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.DateField()),
                ('local', models.CharField(max_length=50)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='juegos.juego')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('alias', models.CharField(max_length=45)),
                ('puntos', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('rol', models.CharField(choices=[('jugador', 'Jugador'), ('anfitrion', 'Anfitrión'), ('admin', 'Admin')], default='anfitrion', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_ganador', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resultados', to='juegos.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugador', to='juegos.userprofile')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_partida', to='juegos.partida')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='juegos.resultado'),
        ),
    ]
