# Generated by Django 3.2.10 on 2025-01-17 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_auto_20250115_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='juegos.resultado'),
        ),
    ]
