# Generated by Django 3.2.10 on 2025-01-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_alter_partida_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateField(),
        ),
    ]
