# Generated by Django 3.2.10 on 2025-01-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_alter_partida_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='partida',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='juegos.local'),
        ),
    ]
