# Generated by Django 3.2.10 on 2025-01-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0005_auto_20250121_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='hora',
            field=models.TimeField(),
        ),
    ]
