# Generated by Django 3.2.10 on 2025-01-23 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juegos', '0006_alter_partida_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidajugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugador', to=settings.AUTH_USER_MODEL),
        ),
    ]
