# Generated by Django 3.2.10 on 2025-01-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0007_alter_partidajugador_jugador'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partidajugador',
            constraint=models.UniqueConstraint(fields=('partida', 'jugador'), name='unique_partida_jugador'),
        ),
    ]
