# Generated by Django 3.2.10 on 2025-02-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0008_partidajugador_unique_partida_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='juegos/static/img')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='imagenes', to='juegos.juego')),
            ],
        ),
    ]
