# Generated by Django 3.2.10 on 2025-02-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0009_juegoimagen'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='juego',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_nombre'),
        ),
    ]
