# Generated by Django 3.2.10 on 2025-02-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0010_juego_unique_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegoimagen',
            name='imagen',
            field=models.ImageField(upload_to='juegos/'),
        ),
    ]
