# Generated by Django 3.2.10 on 2025-02-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0011_alter_juegoimagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
