# Generated by Django 3.2.10 on 2025-02-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0012_alter_juego_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='logo',
            field=models.ImageField(null=True, upload_to='juegos/'),
        ),
    ]
