# Generated by Django 3.2.10 on 2025-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0013_juego_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegoimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
