# Generated by Django 3.2.10 on 2025-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0014_alter_juegoimagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='jugadores/'),
        ),
    ]
