# Generated by Django 3.2.10 on 2025-02-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0016_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(null=True, upload_to='juegos/'),
        ),
    ]
