# Generated by Django 3.2.10 on 2025-02-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0020_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
