# Generated by Django 3.2.10 on 2025-02-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0021_alter_juego_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegoimagen',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='juegos.juego'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='juegos.juego'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='juegos.local'),
        ),
    ]
