# Generated by Django 3.2.10 on 2025-02-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0022_auto_20250213_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
