# Generated by Django 3.2.10 on 2025-02-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0023_auto_20250215_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='juegos.local')),
            ],
        ),
    ]
