# Generated by Django 3.2.10 on 2025-02-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0024_localimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='jugador',
            new_name='ganador',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='puntos',
            new_name='puntaje',
        ),
    ]
