# Generated by Django 3.2.10 on 2025-02-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0025_auto_20250223_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='resultado',
        ),
        migrations.AddField(
            model_name='resultado',
            name='partida',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='juegos.partida'),
        ),
    ]
