# Generated by Django 3.2.10 on 2025-02-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0026_auto_20250223_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='puntaje',
            new_name='puntaje_general',
        ),
        migrations.AddField(
            model_name='partidajugador',
            name='puntaje_general',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
