# Generated by Django 3.2.10 on 2025-02-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0027_auto_20250223_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidajugador',
            old_name='puntaje_general',
            new_name='puntaje',
        ),
    ]
