# Generated by Django 3.2.10 on 2025-02-24 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juegos', '0029_alter_userprofile_puntaje_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='resultados', to=settings.AUTH_USER_MODEL),
        ),
    ]
