# Generated by Django 3.2.10 on 2025-02-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0031_categoria_comentario_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
