# Generated by Django 3.2.10 on 2025-02-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0032_alter_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='respuestas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
