# Generated by Django 3.2.10 on 2025-03-02 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juegos', '0034_auto_20250302_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='juegos.post'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'usuario')},
        ),
    ]
