# Generated by Django 3.2.10 on 2025-03-04 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('juegos', '0036_alter_like_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('usuario', 'content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
    ]
