# Generated by Django 3.2.10 on 2025-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0037_auto_20250303_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='cita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cita',
            field=models.TextField(blank=True, null=True),
        ),
    ]
