# Generated by Django 3.2.10 on 2025-03-25 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0038_auto_20250325_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cita',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.comentario'),
        ),
    ]
