# Generated by Django 3.2.10 on 2025-03-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0039_auto_20250325_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='cita',
            new_name='comentario_cita',
        ),
        migrations.AddField(
            model_name='comentario',
            name='post_cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.post'),
        ),
    ]
