# Generated by Django 3.2.10 on 2025-04-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0040_auto_20250325_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='juegos.comentario')),
            ],
        ),
    ]
