# Generated by Django 3.2.10 on 2025-05-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0043_alter_post_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='juegos.post')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='juegos.comentario')),
            ],
        ),
    ]
