# Generated by Django 3.2.10 on 2025-06-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0045_linkcomment_linkpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjuntoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='juegos.post')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/')),
                ('Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='juegos.comentario')),
            ],
        ),
    ]
