# Generated by Django 3.2.10 on 2025-06-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0046_archivoadjuntocomentario_archivoadjuntopost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivoadjuntocomentario',
            old_name='Comentario',
            new_name='comentario',
        ),
    ]
